# Generated by Django 3.2.8 on 2021-10-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_square',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, height_field='image_square', upload_to='user/', width_field='image_square'),
        ),
    ]
