# Generated by Django 3.2.8 on 2021-10-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211024_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_square',
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, upload_to='user/'),
        ),
    ]
