# Generated by Django 3.2.8 on 2021-10-25 05:19

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211024_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='user/'),
        ),
    ]
