# Generated by Django 3.2.8 on 2021-10-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
